displayName=Giant Rat Transmog
author=Zikkou777
description=Your friends can be rats, you are a rat, everyone is a rat. That's the plugin.
tags=transmog,rat,model,fun,cosmetic
plugins=com.giantrat.GiantRatPlugin
